### ISSUE TITLE
`gatorgrade.yml` file GatorGrader checks

### ISSUE THREAD

**Issue by mariakimheinert** [GatorEducator/gatorgrade#10]
As an instructor, I want to be able to specify GatorGrader checks that correspond to file paths, so that I can verify requirements specific to a file.

**Comment by LiamBlack3** [comment]
Specify checks and make sure that they apply to the file and allowing the customer the room to put checks in that will work.

**Comment by tuduun** [comment]
Command-line generator PR closes this issue
