### ISSUE TITLE
`gatorgrade.yml` non-file GatorGrader checks

### ISSUE THREAD

**Issue by mariakimheinert** [GatorEducator/gatorgrade#11]
As an instructor, I want to be able to specify GatorGrader checks that do not correspond to file paths, so that I can verify behavior that is not file-specific.

**Comment by LiamBlack3** [comment]
We will implement a system where gator grader checks can be more general like checking if a file exists rather than just nested files.

**Comment by Michionlion** [comment]
@LiamBlack3 I think your acceptance criteria here is incorrect. I believe this story specifically talks about checks like `CountCommits`, which requires *no* file context (file context is formed by  the `--file` and `--directory` GatorGrader options). However, file existence (GatorGrader check `ConfirmFileExists`) *does* require a file context.

**Comment by LiamBlack3** [comment]
Okay thank you for your feedback I will edit it!
