### ISSUE TITLE
Set a version of poetry in workflows

### ISSUE THREAD

**Issue by ullrichd21** [GatorEducator/gatorgrade#37]
The workflow should run one specific (preferably the most recent at this time) version of poetry so that it's consistent for the development cycle. That way if there is an update for poetry and we choose to update, we can handle those errors at that time.

**Comment by noorbuchi** [comment]
If I understand this correctly, it looks like this issue has already been resolved while setting up the workflows. Do you think we should close this issue? @ullrichd21

**Comment by ullrichd21** [comment]
Currently, the workflow automatically picks the latest version of poetry. We should force it to use one specific one.
