### ISSUE TITLE
Generated `gatorgrade.yml` should list all files

### ISSUE THREAD

**Issue by mariakimheinert** [GatorEducator/gatorgrade#4]
As an instructor, I want the `gatorgrade.yml` file to list all of the files in the solution repository, so that I can define GatorGrader checks for any file.

**Comment by anthonygc** [comment]
Here is a list of requirements that we hope to achieve to satisfy the customer's goals.

- Parse directory

- Get the directory of all other files within the directory

- Get the name of all subfiles

- Format YML file correctly 

- Document the YML file (for other developers)
