### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by ullrichd21** [GatorEducator/gatorgrade#89]
Is it possible to get a JSON output? I know that will be helpful for integration with other tools? I would take a stab at it but I'd like to hear others thoughts on it before I go about implementing it, or if anyone else wants to do it?

Probably needs a flag in typer to enable that output and then if so just output to terminal in JSON format? Maybe we can also add a file output?

**Comment by Michionlion** [comment]
I'm not sure that's something we want to implement in GatorGrade itself; since they're likely already in a programmatic environment (and thus having a `gatorgrade.yml` is probably not that important) it would be much easier for those who wanted to get JSON output to directly call GatorGrader, like GatorGrade does.

**Comment by mariakimheinert** [comment]
Hi @ullrichd21! Thanks for proposing this interesting idea. Before we invest work into this feature, could you explain in more depth the use cases you imagine for JSON output from GatorGrade? For example, what other tools would it allow GatorGrade to integrate with?
Additionally, could you clarify what you mean by an "events" system? Since events are normally used in large, long-running applications, such as web browsers, it's not obvious how an event system would be necessary to implement JSON output in GatorGrade.
Finally, could you describe the benefits of generating this JSON from GatorGrade, rather than from GatorGrader directly?

**Comment by ullrichd21** [comment]
So in chatting with Prof. Luman, he has been modifying gatorgrader to support various new checks as well as to support lots of new features. One interesting idea was to use gatorgrader output to determine how much of a virtual currency to give students. As such, being able to scrape output, easily, adds to the ability for gatorgrade to interface with other programs. Furthermore, an event system would be very helpful to allow for extensions to be built on top of gatorgrade. The idea being that plugins could subscribe to specific events and run code before or after specific steps in gatorgrade. This would allow for variable features as well since plugins could add features where needed but could be easily stripped for use cases that don't require such features. 

Hopefully that all makes sense. I'd be happy to talk more or explain my thoughts more if need be.

**Comment by Michionlion** [comment]
So, I have a few thoughts on this.

1) An events system, or even a hook system (like git hooks) to enable arbitrary code execution is, in my opinion, too far out of scope for GatorGrade. Instead, a custom GatorGrader check (which can be any arbitrary python file, and could even be packaged with an assignment) should be built for whatever purpose that hook or event would enable; this keeps code encapsulated and reduces overall system complexity.

2) JSON output could be useful, but again I think it is out of scope for GatorGrade; GatorGrader is the "data" producer, and if you need the actual data in machine-readable format, you should be calling GatorGrader directly. GatorGrade is intended to be a user interface, and it should keep that core use in mind. I'm not opposed in principle to JSON output, but I think it distracts from the purpose of GatorGrade. Also, I don't think an event system would be the right way to implement it, if we did decide it was needed.

3) Finally, the work that needs to be done this summer must be aimed at completing and polishing GatorGrade's current functionality (perhaps with usability extensions, such as being able to specify a custom GatorGrader check file, or something similar). I do think JSON output may fit that, but I think it would be a better use of resources to focus on other topics for improvement to get GatorGrade to 1.0 status.


I think that Prof. Luman's ideas would probably be better suited as GatorGrader checks in the first place anyways -- the only hard piece of information to get that would be made easier by integrating with GatorGrade is the full end result of an assignment run. However, that type of information could just as easily be determined by creating something like a "wrapper" GatorGrader check. I think maybe a rudimentary way to convey information like this might be to have the exit code of GatorGrade depend on how many checks failed -- i.e. an exit code of 0 (success) means zero checks failed, whereas an exit code of 2 means that two checks failed. This could make it easier to programmatically determine how "bad" a failure actually was. However, this is a slippery slope -- too much quirkiness like this could make the program harder to use and/or understand for the average user.

Out of curiosity, where is Prof. Luman doing this development? I've seen no additional branches or forks in the GatorGrader repo for quite some time. I'd love to see how he is extending GatorGrader.

**Comment by Michionlion** [comment]
I've been thinking about the JSON output option and what it could enable, and I think I'd propose this structure for it, if we do get around to implementing it:

```bash
gatorgrade --report assignment1.json
```

Essentially, an optional `--report <file>` option for the `gatorgrade` command would write a machine-readable report to the given file, while leaving the standard output of the program unchanged (and still human-readable). This solves one of my biggest concerns with JSON output -- obscuring the actual user interface in favor of machine users. This could make writing a GitHub Actions annotation processor easier, while keeping the log readable, for example. This is actually a direct switch on my previous opinion about file output -- which was a way to express that this felt close to out of scope for GatorGrade. However, after thinking about the use cases you mentioned Prof. Luman was exploring, I think this could meet all of them without obscuring students' view of GatorGrade output or understanding of what is happening. Additionally, it would be a lot less complex than an entire events system!

**Comment by ullrichd21** [comment]
@Michionlion @mariakimheinert 
So I finally got a chance to look at this today and I ran into a slight issue...

The failed checks contains these class references that cannot be serialized into a JSON.
![image](https://user-images.githubusercontent.com/42869122/181654018-1e1cf3d2-9bfe-40c5-8805-c0eff3a8f005.png)
Which is this section here in `run_commands_and_return_results`
```python
    for command in gatorcommands:
        # If command is formatted incorrectly in yaml files,
        # catch the exception that would be returned and print
        try:
            result = gator.grader(command)
        # disable pylint so the more general Exception class can be used
        except Exception as command_exception:  # pylint: disable=W0703
            bad_command = command_exception.__class__
            result = (command, False, bad_command)
        results.append(result)
```
So a potential solution is just to save the stack trace I guess? I don't know what you really want to do here as there really is no *good* way serialize that.

```python
        except Exception:  # pylint: disable=W0703
            result = (command, False, traceback.format_exc())
        results.append(result)
```

**Comment by gkapfham** [comment]
Hello @ullrichd21, the output that you shared in the pastebin URL is fine with me. Do you know if the tool produces similar output for the stack traces when it is run on a different operating system besides Windows? Also, since I am less familiar with the "class references" that can cause the `UnicodeDecodeError` can you please give an example of what those look like? Thanks!
